### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by is8xia** [walking-shadow/deep-learning#3]
就每次跑2个patch就跑不动， log_wandb = wandb.init(project=ph.log_wandb_project, resume='allow', anonymous='must',
                           settings=wandb.Settings(start_method='thread'),
                           config=hyperparameter_dict)这一行代码就报初始化错误，还有怎么改动训练得大小呢，我把patch改动了，但还是每次都训练445张图片，方便的话能加下qq或微信联系吗，我的qq：2064779277，谢谢您

**Comment by walking-shadow** [comment]
应该是wandb库的版本问题，你安装requirements里面wandb对应的版本应该就不会报错了
